### ISSUE TITLE
Curious why run environments from /tmp?

### ISSUE THREAD

**Issue by jorhett** [puppetlabs/kream#22]
I'm curious why the Puppet installation/setup is all done in /tmp rather than the conventional places. Actually curious, not rhetorical, asking for the answer ;-)

In particular, would you accept a patch that (optionally) enabled installation into a named environment in the standard /etc/pl/code/env hierarchy?

**Comment by davejrt** [comment]
We wrote this repo as a way to help us develop the contents of the kubernetes, and subsequently helm and rook modules. 

I can't tell you why we made that decision at the time, and I'm happy to look at a PR but we've previously pointed out when talking about this repo...that it serves as a tool to help us develop the module and quickly as easily as possible. It's not a deployment tool, and we open sourced it as a way for people to use and get familiar with the module before they deploy it using a more scalable method. 

Happy to review PR's but this repo is ultimately best effort with the focus being on the modules themselves.
