### ISSUE TITLE
Building Virtualbox Guest Additions fails

### ISSUE THREAD

**Issue by mattock** [puppetlabs/kream#27]
## Describe the Bug
VirtualBox Guest additions fail to install on box bento/centos-7.5:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:
                                                                                          
mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

## Expected Behavior

VirtualBox Guest additions should install correctly.

## Steps to Reproduce

Destroy any pre-existing cluster nodes (=start from scratch). Then

```
vagrant up kube-master
```

The same behavior can be observed if you run, say,

```
rake cluster_up
```

or

```
bundle exec rake cluster_up
```

## Additional Context

The direct cause of the problem is a mismatch between the running (old) kernel version on the box and the (newer) kernel headers that get installed during VirtualBox Guest Additions installation process.

## The fix

Changing the box from bento/centos-7.5 (outdated) to [bento/centos-7](https://app.vagrantup.com/bento/boxes/centos-7) (up-to-date) seems to fix this particular problem.

**Comment by chelnak** [comment]
Things are looking good for centos deploys now!
